jorani:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:80"
  links:
   - mysql

mysql:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=lms
  volumes:
    - ./db-init:/docker-entrypoint-initdb.d
    - ./mysql:/var/lib/mysql
  ports:
    - 3306:3306
